export function generateReadmeUpdaterScript(): string {
    return [
        "import * as fs from 'fs'",
        "import * as path from 'path'",
        "import { fetchProductiveTime, fetchWeeklyLanguages, fetchWeeklyProjects } from './github-fetcher'",
        "",
        "const README_PATH = path.join(process.cwd(), 'README.md')",
        "const CONFIG_PATH = path.join(process.cwd(), 'glossy-config.json')",
        "",
        "const createBar = (percentage: number, length: number = 25, fillChar: string = '█', emptyChar: string = '░'): string => {",
        "    const safePercentage = Math.max(0, Math.min(100, percentage))",
        "    const filledLength = Math.round((safePercentage / 100) * length)",
        "    return fillChar.repeat(filledLength) + emptyChar.repeat(length - filledLength)",
        "}",
        "",
        "const createSlider = (percentage: number, length: number = 25, lineChar: string = '─', thumbChar: string = '●'): string => {",
        "    const safePercentage = Math.max(0, Math.min(100, percentage))",
        "    const position = Math.round((safePercentage / 100) * (length - 1))",
        "    const before = lineChar.repeat(position)",
        "    const after = lineChar.repeat(Math.max(0, length - 1 - position))",
        "    return before + thumbChar + after",
        "}",
        "",
        "const generateProgressBar = createBar;",
        "",
        "const ProductiveTimeTitles = {",
        "    morning: '🌞 Morning Bird',",
        "    daytime: '☀️ Daytime Hustler',",
        "    evening: '🌆 Evening Contributor',",
        "    night: '🦉 Night Owl',",
        "    flexible: '🌌 Unpredictable Genius'",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "const getDynamicTitle = (style: string, stats: any): string => {",
        "    const { morning, daytime, evening, night } = stats.commits",
        "    const max = Math.max(morning, daytime, evening, night)",
        "    let title = ''",
        "    if (max === morning) title = ProductiveTimeTitles.morning",
        "    else if (max === daytime) title = ProductiveTimeTitles.daytime",
        "    else if (max === evening) title = ProductiveTimeTitles.evening",
        "    else if (max === night) title = ProductiveTimeTitles.night",
        "    else title = ProductiveTimeTitles.flexible",
        "",
        "    return style === 'terminal' ? `>_ ${title}` : title",
        "}",
        "",
        "const generateCyberDeckAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '█', '░')",
        "        return `${icon} ${label.padEnd(14, ' ')} ${count.toString().padStart(6, ' ')} commits    ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        row('🌞', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🌆', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌃', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🌙', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateModernSquareAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '■', '□')",
        "        return `${icon} ${label.toUpperCase().padEnd(14, ' ')} ${count.toString().padStart(6, ' ')} commits     ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        row('🏙️', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🏢', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌉', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🌃', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateMinimalDotAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '●', '○')",
        "        return `${icon} ${label.padEnd(14, ' ')} ${count.toString().padStart(6, ' ')} commits     ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        row('🕕', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🕛', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🕡', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🕛', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateTerminalAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '⣿', '⣀')",
        "        return `> ${label.padEnd(15, ' ')} ${count.toString().padStart(6, ' ')} commits     ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        row('Morning', commits.morning, morning) + '\\n' +",
        "        row('Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('Evening', commits.evening, evening) + '\\n' +",
        "        row('Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateSliderAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createSlider(percentage, 25, '─', '●')",
        "        return `${icon} ${label.padEnd(14, ' ')} ${count.toString().padStart(6, ' ')} commits     ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        row('🕐', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('☀️', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌕', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('💤', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "const generateProductiveTimeAscii = (style: string, stats: any) => {",
        "    const { commits } = stats",
        "    const total = commits.morning + commits.daytime + commits.evening + commits.night",
        "    if (total === 0) return '```text\\n        [zzz]\\n       ( -_-)\\n      /|    |\\\\\\\\\\n     / |    | \\\\\\\\\\n    ￣￣￣￣￣￣￣\\n  Currently taking a coffee break ☕\\n  (No public activity found... yet!)\\n```\\n'",
        "",
        "    let ascii = ''",
        "    if (style === 'modern') ascii = generateModernSquareAscii(stats)",
        "    else if (style === 'minimal') ascii = generateMinimalDotAscii(stats)",
        "    else if (style === 'terminal') ascii = generateTerminalAscii(stats)",
        "    else if (style === 'slider') ascii = generateSliderAscii(stats)",
        "    else ascii = generateCyberDeckAscii(stats)",
        "    ",
        "    return getDynamicTitle(style, stats) + '\\n' + ascii",
        "}",
        "",
        "async function updateReadme() {",
        "    try {",
        "        console.log('📖 Reading existing README.md...')",
        "        const readmeContent = fs.readFileSync(README_PATH, 'utf-8')",
        "        ",
        "        console.log('⚙️ Loading glossy-config.json...')",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let config: any;",
        "        try {",
        "            const fileContent = fs.readFileSync(CONFIG_PATH, 'utf-8')",
        "            const cleanContent = fileContent.replace(/^\\s*\\/\\/.*$/gm, '')",
        "            config = JSON.parse(cleanContent)",
        "        } catch (e: any) {",
        "            console.error('❌ Failed to read or parse config JSON. Please make sure glossy-config.json exists in the root directory.')",
        "            console.error('Error details:', e.message)",
        "            process.exit(1)",
        "        }",
        "        ",
        "        let newReadme = readmeContent",
        "        const blocks = config.blocks || []",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const dynamicBlocks = blocks.filter((b: any) => b.type === 'widget')",
        "",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let timeData: any = null;",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let langData: any = null;",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let projData: any = null;",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        if (dynamicBlocks.some((b: any) => b.widgetType === 'productive-time')) {",
        "            timeData = await fetchProductiveTime(config.username)",
        "        }",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        if (dynamicBlocks.some((b: any) => b.widgetType === 'weekly-languages')) {",
        "            langData = await fetchWeeklyLanguages(config.username)",
        "        }",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        if (dynamicBlocks.some((b: any) => b.widgetType === 'weekly-projects')) {",
        "            projData = await fetchWeeklyProjects(config.username)",
        "        }",
        "",
        "        for (const block of dynamicBlocks) {",
        "            console.log(`🔄 Updating widget: ${block.widgetType} (ID: ${block.id})`)",
        "            ",
        "            const startMarker = `<!-- glossy-${block.widgetType}-${block.id}-start -->`",
        "            const endMarker = `<!-- glossy-${block.widgetType}-${block.id}-end -->`",
        "            ",
        "            const startIndex = newReadme.indexOf(startMarker)",
        "            const endIndex = newReadme.indexOf(endMarker)",
        "",
        "            if (startIndex !== -1 && endIndex !== -1) {",
        "                let markdownToInject = ''",
        "                const bConf = block.config || {}",
        "                ",
        "                switch(block.widgetType) {",
        "                    case 'productive-time':",
        "                        const style = bConf.productiveTime?.style || config.productiveTime?.style || 'cyber'",
        "                        markdownToInject = '\\n' + generateProductiveTimeAscii(style, timeData)",
        "                        break",
        "                        ",
        "                    case 'weekly-languages':",
        "                        const lConf = bConf.weeklyLanguages || config.weeklyLanguages || {}",
        "                        const lPeriod = lConf.periodDays || 7",
        "                        const lPeriodStr = lPeriod === 7 ? '(Last Week)' : lPeriod === 14 ? '(Last 2 Weeks)' : `(Last ${lPeriod} Days)`",
        "                        const title = bConf.title || `💬 Weekly Languages ${lPeriodStr}`",
        "                        const lLimit = lConf.count || config.activityStats?.itemCount || 5",
        "                        const excludes = lConf.excludeLanguages || []",
        "                        ",
        "                        const sortedLang = [...(langData || [])]",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        if (lConf.sortBy === 'alphabetical') sortedLang.sort((a: any, b: any) => a.name.localeCompare(b.name))",
        "                        ",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        const filteredLang = sortedLang.filter((l: any) => !excludes.includes(l.name)).slice(0, lLimit)",
        "                        ",
        "                        markdownToInject = '\\n```text\\n' + title + '\\n\\n'",
        "                        if (filteredLang.length === 0) {",
        "                            markdownToInject += '   ╭────────────────────────────╮\\n' +",
        "                                '   │   NO ACTIVITY DETECTED     │\\n' +",
        "                                '   │   Waiting for daily code.  │\\n' +",
        "                                '   ╰────────────────────────────╯\\n'",
        "                        } else {",
        "                            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                            filteredLang.forEach((lang: any) => {",
        "                                const bar = generateProgressBar(lang.percent, 25)",
        "                                const namePad = lang.name.padEnd(15, ' ')",
        "                                const statPad = `${lang.count} Repos`.padEnd(15, ' ')",
        "                                const percentPad = `${lang.percent} %`.padStart(7, ' ')",
        "                                markdownToInject += `${namePad} ${statPad} ${bar} ${percentPad}\\n`",
        "                            })",
        "                        }",
        "                        markdownToInject += '```\\n'",
        "                        break",
        "                        ",
        "                    case 'weekly-projects':",
        "                        const pConf = bConf.weeklyProjects || config.weeklyProjects || {}",
        "                        const pPeriod = pConf.periodDays || 7",
        "                        const pPeriodStr = pPeriod === 7 ? '(Last Week)' : pPeriod === 14 ? '(Last 2 Weeks)' : `(Last ${pPeriod} Days)`",
        "                        const pTitle = bConf.title || `🐱💻 Weekly Projects ${pPeriodStr}`",
        "                        const pLimit = pConf.count || config.activityStats?.itemCount || 5",
        "                        ",
        "                        const sortedProj = [...(projData || [])]",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        if (pConf.sortBy === 'alphabetical') sortedProj.sort((a: any, b: any) => a.name.localeCompare(b.name))",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        else if (pConf.sortBy === 'commits') sortedProj.sort((a: any, b: any) => b.commits - a.commits)",
        "                        ",
        "                        const finalProj = sortedProj.slice(0, pLimit)",
        "                        ",
        "                        markdownToInject = '\\n```text\\n' + pTitle + '\\n\\n'",
        "                        if (finalProj.length === 0) {",
        "                            markdownToInject += '     .-.\\n' +",
        "                                '   (o o) boo!\\n' +",
        "                                '   | O \\\\\\\\\\n' +",
        "                                '    \\\\\\\\   \\\\\\\\\\n' +",
        "                                '     \\'~~~\\'\\n' +",
        "                                '  Invisible on the radar! 👻\\n' +",
        "                                '  (Or maybe just working in private repos...)\\n'",
        "                        } else {",
        "                            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                            finalProj.forEach((proj: any) => {",
        "                                const bar = generateProgressBar(proj.percent, 25)",
        "                                const namePad = proj.name.padEnd(20, ' ')",
        "                                const statPad = `${proj.commits} commits`.padEnd(15, ' ')",
        "                                const percentPad = `${proj.percent} %`.padStart(7, ' ')",
        "                                markdownToInject += `${namePad} ${statPad} ${bar} ${percentPad}\\n`",
        "                            })",
        "                        }",
        "                        markdownToInject += '```\\n'",
        "                        break",
        "                }",
        "",
        "                newReadme = newReadme.substring(0, startIndex + startMarker.length) +",
        "                    markdownToInject.trimEnd() + '\\n' +",
        "                    newReadme.substring(endIndex)",
        "            } else {",
        "                console.warn(`⚠️ Markers not found for widget: ${block.widgetType}`)",
        "            }",
        "        }",
        "",
        "        fs.writeFileSync(README_PATH, newReadme, 'utf-8')",
        "        console.log('✅ README updated successfully!')",
        "    } catch (error) {",
        "        console.error('❌ Failed to update README:', error)",
        "        process.exit(1)",
        "    }",
        "}",
        "",
        "updateReadme()"
    ].join('\n');
}

export function generateGithubFetcherScript(): string {
    return [
        "const GITHUB_TOKEN = process.env.GITHUB_TOKEN || ''",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "async function fetchGithub(url: string, options: any = {}) {",
        "    const res = await fetch(url, {",
        "        ...options,",
        "        headers: {",
        "            'Authorization': `Bearer ${GITHUB_TOKEN}`,",
        "            'Accept': 'application/vnd.github.v3+json',",
        "            ...(options.headers || {})",
        "        }",
        "    })",
        "    if (!res.ok) throw new Error(`GitHub API failed: ${res.status}`)",
        "    return res.json()",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "async function fetchGraphql(query: string, variables: any = {}) {",
        "    const res = await fetch('https://api.github.com/graphql', {",
        "        method: 'POST',",
        "        headers: {",
        "            'Authorization': `Bearer ${GITHUB_TOKEN}`,",
        "            'Content-Type': 'application/json'",
        "        },",
        "        body: JSON.stringify({ query, variables })",
        "    })",
        "    if (!res.ok) throw new Error(`GraphQL fetch failed: ${res.status}`)",
        "    return res.json()",
        "}",
        "",
        "export async function fetchProductiveTime(username: string) {",
        "    try {",
        "        const events = await fetchGithub(`https://api.github.com/users/${username}/events/public?per_page=100`)",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const pushEvents = events.filter((e: any) => e.type === 'PushEvent')",
        "        ",
        "        const timeBuckets = { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "        let totalCommits = 0",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        pushEvents.forEach((event: any) => {",
        "            const hour = new Date(event.created_at).getHours()",
        "            if (hour >= 6 && hour < 12) timeBuckets.morning++",
        "            else if (hour >= 12 && hour < 18) timeBuckets.daytime++",
        "            else if (hour >= 18 && hour < 24) timeBuckets.evening++",
        "            else timeBuckets.night++",
        "            totalCommits++",
        "        })",
        "        ",
        "        if (totalCommits === 0) {",
        "            return {",
        "                morning: 0, daytime: 0, evening: 0, night: 0,",
        "                commits: { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "            }",
        "        }",
        "        ",
        "        return {",
        "            morning: Math.round((timeBuckets.morning / totalCommits) * 100),",
        "            daytime: Math.round((timeBuckets.daytime / totalCommits) * 100),",
        "            evening: Math.round((timeBuckets.evening / totalCommits) * 100),",
        "            night: Math.round((timeBuckets.night / totalCommits) * 100),",
        "            commits: timeBuckets",
        "        }",
        "    } catch (e) {",
        "        console.warn('Failed to fetch productive time:', e)",
        "        return {",
        "            morning: 0, daytime: 0, evening: 0, night: 0,",
        "            commits: { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "        }",
        "    }",
        "}",
        "",
        "export async function fetchWeeklyLanguages(username: string) {",
        "    try {",
        "        const query = `",
        "            query($login: String!) {",
        "                user(login: $login) {",
        "                    repositories(first: 100, isFork: false, orderBy: {field: PUSHED_AT, direction: DESC}) {",
        "                        nodes {",
        "                            languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {",
        "                                edges { size node { name } }",
        "                            }",
        "                        }",
        "                    }",
        "                }",
        "            }",
        "        `",
        "        const { data } = await fetchGraphql(query, { login: username })",
        "        ",
        "        const langMap = new Map()",
        "        let totalBytes = 0",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        for (const repo of data.user.repositories.nodes) {",
        "            if (!repo.languages?.edges) continue",
        "            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "            for (const { size, node } of repo.languages.edges) {",
        "                const current = langMap.get(node.name) || { size: 0, count: 0 }",
        "                langMap.set(node.name, { size: current.size + size, count: current.count + 1 })",
        "                totalBytes += size",
        "            }",
        "        }",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const results = Array.from(langMap.entries()).map(([name, val]: any) => ({",
        "            name,",
        "            count: val.count,",
        "            percent: totalBytes > 0 ? Math.round((val.size / totalBytes) * 100 * 100) / 100 : 0",
        "        }))",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        return results.sort((a: any, b: any) => b.percent - a.percent)",
        "    } catch (e) {",
        "        console.warn('Failed to fetch languages:', e)",
        "        return []",
        "    }",
        "}",
        "",
        "export async function fetchWeeklyProjects(username: string) {",
        "    try {",
        "        const query = `",
        "            query($login: String!) {",
        "                user(login: $login) {",
        "                    repositories(first: 100, isFork: false, orderBy: {field: PUSHED_AT, direction: DESC}) {",
        "                        nodes {",
        "                            name",
        "                            defaultBranchRef {",
        "                                target { ... on Commit { history(author: {id: $login}) { totalCount } } }",
        "                            }",
        "                        }",
        "                    }",
        "                }",
        "            }",
        "        `",
        "        const { data } = await fetchGraphql(query, { login: username })",
        "        ",
        "        let results: Array<{name: string, commits: number, percent?: number}> = []",
        "        let totalCommits = 0",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        for (const repo of data.user.repositories.nodes) {",
        "            const commits = repo.defaultBranchRef?.target?.history?.totalCount || 0",
        "            if (commits > 0) {",
        "                results.push({ name: repo.name, commits })",
        "                totalCommits += commits",
        "            }",
        "        }",
        "        ",
        "        results = results.map(r => ({",
        "            ...r,",
        "            percent: totalCommits > 0 ? Math.round((r.commits / totalCommits) * 100 * 100) / 100 : 0",
        "        }))",
        "        ",
        "        return results.sort((a,b) => b.commits - a.commits)",
        "    } catch (e) {",
        "        console.warn('Failed to fetch projects:', e)",
        "        return []",
        "    }",
        "}"
    ].join('\n');
}

export function generatePackageJson(): string {
    return [
        "{",
        "  \"name\": \"github-profile-automation\",",
        "  \"version\": \"1.0.0\",",
        "  \"description\": \"Auto-updater for Glossy GitHub Profile\",",
        "  \"main\": \"scripts/update-readme.ts\",",
        "  \"scripts\": {",
        "    \"update-profile\": \"ts-node scripts/update-readme.ts\"",
        "  },",
        "  \"dependencies\": {",
        "    \"ts-node\": \"^10.9.1\",",
        "    \"typescript\": \"^5.0.0\",",
        "    \"@types/node\": \"^18.0.0\"",
        "  },",
        "  \"ts-node\": {",
        "    \"compilerOptions\": {",
        "      \"module\": \"CommonJS\"",
        "    }",
        "  }",
        "}"
    ].join('\\n');
}

export function generateTsConfig(): string {
    return [
        "{",
        "  \"compilerOptions\": {",
        "    \"target\": \"ES2022\",",
        "    \"module\": \"CommonJS\",",
        "    \"moduleResolution\": \"node\",",
        "    \"esModuleInterop\": true,",
        "    \"skipLibCheck\": true,",
        "    \"forceConsistentCasingInFileNames\": true",
        "  }",
        "}"
    ].join('\\n');
}
