export function generateReadmeUpdaterScript(hasGithub: boolean = true, hasWakatime: boolean = false): string {
    return [
        "import * as fs from 'fs'",
        "import * as path from 'path'",
        hasGithub ? "import { fetchProductiveTime, fetchUserRepositories, fetchUserEvents, calculateWeeklyLanguages, calculateWeeklyProjects } from './github-fetcher'" : "",
        hasWakatime ? "import { fetchWakatimeStats } from './wakatime-fetcher'" : "",
        "",
        "const README_PATH = path.join(process.cwd(), 'README.md')",
        "const CONFIG_PATH = path.join(process.cwd(), 'glossy-config.json')",
        "",
        "const createBar = (percentage: number, length: number = 25, fillChar: string = '█', emptyChar: string = '░'): string => {",
        "    const safePercentage = Math.max(0, Math.min(100, percentage))",
        "    const filledLength = Math.round((safePercentage / 100) * length)",
        "    return fillChar.repeat(filledLength) + emptyChar.repeat(length - filledLength)",
        "}",
        "",
        "const createSlider = (percentage: number, length: number = 25, lineChar: string = '─', thumbChar: string = '●'): string => {",
        "    const safePercentage = Math.max(0, Math.min(100, percentage))",
        "    const position = Math.round((safePercentage / 100) * (length - 1))",
        "    const before = lineChar.repeat(position)",
        "    const after = lineChar.repeat(Math.max(0, length - 1 - position))",
        "    return before + thumbChar + after",
        "}",
        "",
        "const generateProgressBar = createBar;",
        "",
        "const THEME_COLORS = [",
        "    { id: 'blue', emoji: { square: '🟦', circle: '🔵' } },",
        "    { id: 'green', emoji: { square: '🟩', circle: '🟢' } },",
        "    { id: 'purple', emoji: { square: '🟪', circle: '🟣' } },",
        "    { id: 'orange', emoji: { square: '🟧', circle: '🟠' } },",
        "    { id: 'red', emoji: { square: '🟥', circle: '🔴' } }",
        "]",
        "",
        "const generateEmojiBar = (percent: number, filledEmoji: string = '🟦', size: number = 10) => {",
        "    const safePercentage = Math.max(0, Math.min(100, percent))",
        "    const filled = Math.round((size * safePercentage) / 100)",
        "    const empty = size - filled",
        "    return filledEmoji.repeat(filled) + '⬜'.repeat(empty)",
        "}",
        "",
        "const generateCompactBadge = (colorEmoji: string = '🔵') => {",
        "    return colorEmoji",
        "}",
        "",
        "const ProductiveTimeTitles = {",
        "    morning: \"I'm an Early Bird 🌞\",",
        "    daytime: \"I'm a Daytime Coder ☀️\",",
        "    evening: \"I'm an Evening Developer 🌆\",",
        "    night: \"I'm a Night Owl 🦉\",",
        "    flexible: \"I'm a Flexible Developer 🌈\"",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "const getDynamicTitle = (style: string, stats: any): string => {",
        "    const { morning, daytime, evening, night } = stats",
        "    const max = Math.max(morning, daytime, evening, night)",
        "    let title = ''",
        "    if (max === morning) title = ProductiveTimeTitles.morning",
        "    else if (max === daytime) title = ProductiveTimeTitles.daytime",
        "    else if (max === evening) title = ProductiveTimeTitles.evening",
        "    else if (max === night) title = ProductiveTimeTitles.night",
        "    else title = ProductiveTimeTitles.flexible",
        "",
        "    if (style === 'terminal') return `>_ ${title}`",
        "    return title",
        "}",
        "",
        "const generateCyberDeckAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '█', '░')",
        "        const labelPad = label.padEnd(25, ' ')",
        "        const statPad = `${count.toString().padStart(8, ' ')} commits`.padEnd(26, ' ')",
        "        return `${icon} ${labelPad} ${statPad} ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        `${getDynamicTitle('cyber', stats)}\\n\\n` +",
        "        row('🌞', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🌆', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌃', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🌙', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateModernSquareAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '■', '□')",
        "        const labelPad = label.toUpperCase().padEnd(25, ' ')",
        "        const statPad = `${count.toString().padStart(8, ' ')} commits`.padEnd(26, ' ')",
        "        return `${icon} ${labelPad} ${statPad} ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        `${getDynamicTitle('modern', stats)}\\n\\n` +",
        "        row('🏙️', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🏢', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌉', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🌃', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateMinimalDotAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '●', '○')",
        "        const labelPad = label.padEnd(25, ' ')",
        "        const statPad = `${count.toString().padStart(8, ' ')} commits`.padEnd(26, ' ')",
        "        return `${icon} ${labelPad} ${statPad} ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        `${getDynamicTitle('minimal', stats)}\\n\\n` +",
        "        row('🕕', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('🕛', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🕡', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('🕛', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateTerminalAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (label: string, count: number, percentage: number) => {",
        "        const bar = createBar(percentage, 25, '⣿', '⣀')",
        "        const labelPad = label.padEnd(26, ' ')",
        "        const statPad = `${count.toString().padStart(8, ' ')} commits`.padEnd(26, ' ')",
        "        return `> ${labelPad} ${statPad} ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        `${getDynamicTitle('terminal', stats)}\\n\\n` +",
        "        row('Morning', commits.morning, morning) + '\\n' +",
        "        row('Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('Evening', commits.evening, evening) + '\\n' +",
        "        row('Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "const generateSliderAscii = (stats: any) => {",
        "    const { morning, daytime, evening, night, commits } = stats",
        "    const row = (icon: string, label: string, count: number, percentage: number) => {",
        "        const bar = createSlider(percentage, 25, '─', '●')",
        "        const labelPad = label.padEnd(25, ' ')",
        "        const statPad = `${count.toString().padStart(8, ' ')} commits`.padEnd(26, ' ')",
        "        return `${icon} ${labelPad} ${statPad} ${bar}    ${percentage.toFixed(2).padStart(5, '0')} %`",
        "    }",
        "    return '```text\\n' +",
        "        `${getDynamicTitle('slider', stats)}\\n\\n` +",
        "        row('🕐', 'Morning', commits.morning, morning) + '\\n' +",
        "        row('☀️', 'Daytime', commits.daytime, daytime) + '\\n' +",
        "        row('🌕', 'Evening', commits.evening, evening) + '\\n' +",
        "        row('💤', 'Night', commits.night, night) + '\\n' +",
        "        '```\\n'",
        "}",
        "",
        ...(hasWakatime ? [
            "function LIMIT_LENGTH(len: number) { return len > 0 ? len : 0 }",
            "const generateWaka10kHoursAscii = (wakaData: any, bConf: any, config: any) => {",
            "    const theme = bConf.theme || 'classic'",
            "    const targetLanguage = bConf.targetLanguage || 'TypeScript'",
            "    const goalTitle = bConf.goalTitle || `Master of ${targetLanguage}`",
            "    const displayMode = bConf.displayMode || 'accumulated'",
            "",
            "    const targetLangData = wakaData?.languages?.find((l: any) => l.name === targetLanguage)",
            "    ",
            "    let stateMessage = ''",
            "    if (wakaData?.isCalculating) {",
            "        stateMessage = 'WakaTime is currently calculating your all-time stats for the first time. Please check back in a few minutes.'",
            "    } else if (wakaData?.success === false) {",
            "        stateMessage = 'Failed to fetch WakaTime stats.'",
            "    }",
            "",
            "    const totalSeconds = (!stateMessage && targetLangData) ? targetLangData.total_seconds || 0 : 0",
            "    const totalHours = Number((totalSeconds / 3600).toFixed(1))",
            "    ",
            "    const goalHours = 10000",
            "    let pctNumber = (totalHours / goalHours) * 100",
            "    if (pctNumber > 100) pctNumber = 100",
            "    const percentage = pctNumber.toFixed(2)",
            "    const remainingHours = Number(Math.max(0, goalHours - totalHours).toFixed(1))",
            "    const level = Math.floor(totalHours / 100) + 1",
            "",
            "    let markdown = '```text\\n'",
            "    markdown += `${goalTitle}\\n\\n`",
            "",
            "    if (stateMessage) {",
            "        if (theme === 'classic') {",
            "            markdown += `${targetLanguage} Proficiency\\n`",
            "            markdown += `[ SYSTEM STATUS ]\\n`",
            "            markdown += `> ${stateMessage}\\n`",
            "        } else if (theme === 'rpg') {",
            "            markdown += `> ⚔️ [CLASS: ${targetLanguage} Artisan]\\n`",
            "            markdown += `> ⏳ SYSTEM ALERTS:\\n`",
            "            markdown += `>    ${stateMessage}\\n`",
            "        } else if (theme === 'terminal') {",
            "            markdown += `guest@github:~$ wakatime --lang \"${targetLanguage}\" \\n`",
            "            markdown += `> WARN: ${stateMessage}\\n`",
            "        } else if (theme === 'minimal') {",
            "            markdown += `LANGUAGE     LOGGED TIME         PROGRESS\\n`",
            "            markdown += `${targetLanguage.padEnd(12, ' ')} [ ${stateMessage} ]\\n`",
            "        }",
            "    } else if (theme === 'classic') {",
            "        const chartBlocks = Math.floor(pctNumber / 5)",
            "        const filled = '█'.repeat(chartBlocks)",
            "        const empty = '░'.repeat(20 - chartBlocks)",
            "        if (displayMode === 'accumulated') {",
            "            markdown += `Total: ${totalHours.toLocaleString()} Hours\\n`",
            "        } else {",
            "            markdown += `${remainingHours.toLocaleString()} Hours to mastery\\n`",
            "        }",
            "        markdown += `[${filled}${empty}] ${percentage}%\\n`",
            "    } else if (theme === 'rpg') {",
            "        const chartBlocks = Math.floor(pctNumber / 5)",
            "        const filled = '▓'.repeat(chartBlocks)",
            "        const empty = '┈'.repeat(LIMIT_LENGTH(20 - chartBlocks))",
            "        markdown += `> ⚔️ [CLASS: ${targetLanguage} Artisan]\\n`",
            "        if (displayMode === 'accumulated') {",
            "            markdown += `> 📊 EXP: ${totalHours.toLocaleString()} / 10,000 (Lv. ${level})\\n`",
            "        } else {",
            "            markdown += `> 🎯 REMAINING: ${remainingHours.toLocaleString()} Hours to mastery\\n`",
            "        }",
            "        markdown += `> 📈 [${filled}${empty}]\\n`",
            "    } else if (theme === 'terminal') {",
            "        const filledTotal = Math.floor(pctNumber / 4)",
            "        const fillCount = LIMIT_LENGTH(filledTotal > 0 ? filledTotal - 1 : 0)",
            "        const filled = '='.repeat(fillCount) + (filledTotal > 0 ? '>' : '')",
            "        const empty = ' '.repeat(LIMIT_LENGTH(25 - filledTotal))",
            "        markdown += `guest@github:~$ wakatime --lang \"${targetLanguage}\" \\n`",
            "        markdown += `[${filled}${empty}] ${percentage}%\\n`",
            "        markdown += `> ${totalHours.toLocaleString()} hours logged.\\n`",
            "        markdown += `> ${displayMode === 'accumulated' ? 'Ongoing progress...' : `${remainingHours.toLocaleString()} hours remaining.`}\\n`",
            "    } else if (theme === 'minimal') {",
            "        const chartBlocks = Math.floor(pctNumber / 10)",
            "        const filled = '█'.repeat(chartBlocks)",
            "        const empty = '░'.repeat(10 - chartBlocks)",
            "        const namePad = targetLanguage.padEnd(12, ' ')",
            "        const hoursPad = (displayMode === 'accumulated' ? `${totalHours.toLocaleString()} hrs` : `${remainingHours.toLocaleString()} hrs`).padStart(14, ' ')",
            "        const barPad = `${filled}${empty} (${percentage}%)`.padStart(18, ' ')",
            "        const headerTime = (displayMode === 'accumulated' ? 'LOGGED TIME' : 'REMAINING TIME').padStart(14, ' ')",
            "        markdown += `LANGUAGE         ${headerTime}   PROGRESS\\n`",
            "        markdown += `${namePad}     ${hoursPad}   ${barPad}\\n`",
            "    }",
            "    markdown += '```\\n'",
            "    return markdown",
            "}"
        ] : []),
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "const generateProductiveTimeAscii = (style: string, stats: any) => {",
        "    const { commits } = stats",
        "    const total = commits.morning + commits.daytime + commits.evening + commits.night",
        "    if (total === 0) return '```text\\n        [zzz]\\n       ( -_-)\\n      /|    |\\\\\\\\\\n     / |    | \\\\\\\\\\n    ￣￣￣￣￣￣￣\\n  Currently taking a coffee break ☕\\n  (No public activity found... yet!)\\n```\\n'",
        "",
        "    let ascii = ''",
        "    if (style === 'modern') ascii = generateModernSquareAscii(stats)",
        "    else if (style === 'minimal') ascii = generateMinimalDotAscii(stats)",
        "    else if (style === 'terminal') ascii = generateTerminalAscii(stats)",
        "    else if (style === 'slider') ascii = generateSliderAscii(stats)",
        "    else ascii = generateCyberDeckAscii(stats)",
        "    ",
        "    return ascii",
        "}",
        "",
        "async function updateReadme() {",
        "    try {",
        "        console.log('📖 Reading existing README.md...')",
        "        const readmeContent = fs.readFileSync(README_PATH, 'utf-8')",
        "        ",
        "        console.log('⚙️ Loading glossy-config.json...')",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let config: any;",
        "        try {",
        "            const fileContent = fs.readFileSync(CONFIG_PATH, 'utf-8')",
        "            const cleanContent = fileContent.replace(/^\\s*\\/\\/.*$/gm, '')",
        "            config = JSON.parse(cleanContent)",
        "        } catch (e: any) {",
        "            console.error('❌ Failed to read or parse config JSON. Please make sure glossy-config.json exists in the root directory.')",
        "            console.error('Error details:', e.message)",
        "            process.exit(1)",
        "        }",
        "        ",
        "        let newReadme = readmeContent",
        "        const blocks = config.blocks || []",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const dynamicBlocks = blocks.filter((b: any) => b.type === 'widget')",
        "",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let timeData: any = null;",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let langData: any = null;",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let projData: any = null;",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        let wakaData: any = null;",
        "        ",
        ...(hasGithub ? [
            "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
            "        if (dynamicBlocks.some((b: any) => b.widgetType === 'productive-time')) {",
            "            timeData = await fetchProductiveTime(config.username)",
            "        }",
            "        const needsRepos = dynamicBlocks.some((b: any) => b.widgetType === 'weekly-languages')",
            "        const needsEvents = dynamicBlocks.some((b: any) => b.widgetType === 'weekly-projects')",
            "        let rawRepos: any = []",
            "        let rawEvents: any = []",
            "        if (needsRepos) {",
            "            rawRepos = await fetchUserRepositories(config.username)",
            "        }",
            "        if (needsEvents) {",
            "            rawEvents = await fetchUserEvents(config.username)",
            "        }",
            "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
            "        if (dynamicBlocks.some((b: any) => b.widgetType === 'weekly-languages')) {",
            "            langData = calculateWeeklyLanguages(rawRepos)",
            "        }",
            "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
            "        if (dynamicBlocks.some((b: any) => b.widgetType === 'weekly-projects')) {",
            "            projData = calculateWeeklyProjects(rawEvents)",
            "        }"
        ] : []),
        ...(hasWakatime ? [
            "        if (dynamicBlocks.some((b: any) => b.widgetType === 'waka-10k-hours')) {",
            "            wakaData = await fetchWakatimeStats()",
            "        }"
        ] : []),
        "",
        "        for (const block of dynamicBlocks) {",
        "            console.log(`🔄 Updating widget: ${block.widgetType} (ID: ${block.id})`)",
        "            ",
        "            const startMarker = `<!-- glossy-${block.widgetType}-${block.id}-start -->`",
        "            const endMarker = `<!-- glossy-${block.widgetType}-${block.id}-end -->`",
        "            ",
        "            const startIndex = newReadme.indexOf(startMarker)",
        "            const endIndex = newReadme.indexOf(endMarker)",
        "",
        "            if (startIndex !== -1 && endIndex !== -1) {",
        "                let markdownToInject = ''",
        "                const bConf = block.config || {}",
        "                ",
        "                switch(block.widgetType) {",
        "                    case 'productive-time':",
        "                        const style = bConf.productiveTime?.style || config.productiveTime?.style || 'cyber'",
        "                        markdownToInject = '\\n' + generateProductiveTimeAscii(style, timeData)",
        "                        break",
        "                        ",
        "                    case 'weekly-languages':",
        "                        const lConf = bConf.weeklyLanguages || config.weeklyLanguages || {}",

        "                        const title = bConf.title || `💬 Weekly Languages`",
        "                        const lLimit = lConf.count || config.activityStats?.itemCount || 5",
        "                        const excludes = lConf.excludeLanguages || []",
        "                        ",
        "                        const sortedLang = [...(langData || [])]",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        if (lConf.sortBy === 'alphabetical') sortedLang.sort((a: any, b: any) => a.name.localeCompare(b.name))",
        "                        ",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        const filteredLang = sortedLang.filter((l: any) => !excludes.includes(l.name)).slice(0, lLimit)",
        "                        const visualizationStyle = lConf.style || 'progress'",
        "                        const themeColor = lConf.themeColor || 'blue'",
        "                        const emojis = THEME_COLORS.find(c => c.id === themeColor)?.emoji || THEME_COLORS[0].emoji",
        "                        ",
        "                        markdownToInject = '\\n```text\\n' + title + '\\n\\n'",
        "                        if (filteredLang.length === 0) {",
        "                            markdownToInject += '   ╭────────────────────────────╮\\n' +",
        "                                '   │   NO ACTIVITY DETECTED     │\\n' +",
        "                                '   │   Waiting for daily code.  │\\n' +",
        "                                '   ╰────────────────────────────╯\\n'",
        "                        } else {",
        "                            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                            filteredLang.forEach((lang: any) => {",
        "                                let bar = ''",
        "                                if (visualizationStyle === 'progress') bar = generateProgressBar(lang.percent, 25)",
        "                                else if (visualizationStyle === 'emoji') bar = generateEmojiBar(lang.percent, emojis.square, 10)",
        "                                else if (visualizationStyle === 'compact') bar = generateCompactBadge(emojis.circle)",
        "                                ",
        "                                const safeName = lang.name.length > 26 ? lang.name.substring(0, 26) + '..' : lang.name",
        "                                const namePad = safeName.padEnd(28, ' ')",
        "                                const repoStr = String(lang.count).padStart(8, ' ')",
        "                                const statPad = `${repoStr} Repos`.padEnd(26, ' ')",
        "                                const percentPad = `${lang.percent} %`.padStart(8, ' ')",
        "                                markdownToInject += `${namePad} ${statPad} ${bar} ${percentPad}\\n`",
        "                            })",
        "                        }",
        "                        markdownToInject += '```\\n'",
        "                        break",
        "                        ",
        "                    case 'weekly-projects':",
        "                        const pConf = bConf.weeklyProjects || config.weeklyProjects || {}",

        "                        const pTitle = bConf.title || `🐱💻 Weekly Projects`",
        "                        const pLimit = pConf.count || config.activityStats?.itemCount || 5",
        "                        ",
        "                        const sortedProj = [...(projData || [])]",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        if (pConf.sortBy === 'alphabetical') sortedProj.sort((a: any, b: any) => a.name.localeCompare(b.name))",
        "                        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                        else if (pConf.sortBy === 'commits') sortedProj.sort((a: any, b: any) => b.commits - a.commits)",
        "                        ",
        "                        const finalProj = sortedProj.slice(0, pLimit)",
        "                        const pVisualizationStyle = pConf.style || 'progress'",
        "                        const pThemeColor = pConf.themeColor || 'green'",
        "                        const pEmojis = THEME_COLORS.find(c => c.id === pThemeColor)?.emoji || THEME_COLORS[1].emoji",
        "                        ",
        "                        markdownToInject = '\\n```text\\n' + pTitle + '\\n\\n'",
        "                        if (finalProj.length === 0) {",
        "                            markdownToInject += '     .-.\\n' +",
        "                                '   (o o) boo!\\n' +",
        "                                '   | O \\\\\\\\\\n' +",
        "                                '    \\\\\\\\   \\\\\\\\\\n' +",
        "                                '     \\'~~~\\'\\n' +",
        "                                '  Invisible on the radar! 👻\\n' +",
        "                                '  (Or maybe just working in private repos...)\\n'",
        "                        } else {",
        "                            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "                            finalProj.forEach((proj: any) => {",
        "                                let bar = ''",
        "                                if (pVisualizationStyle === 'progress') bar = generateProgressBar(proj.percent, 25)",
        "                                else if (pVisualizationStyle === 'emoji') bar = generateEmojiBar(proj.percent, pEmojis.square, 10)",
        "                                else if (pVisualizationStyle === 'compact') bar = generateCompactBadge(pEmojis.circle)",
        "                                ",
        "                                const safeName = proj.name.length > 26 ? proj.name.substring(0, 26) + '..' : proj.name",
        "                                const namePad = safeName.padEnd(28, ' ')",
        "                                const commitsStr = String(proj.commits).padStart(8, ' ')",
        "                                const statPad = `${commitsStr} contribs`.padEnd(26, ' ')",
        "                                const percentPad = `${proj.percent} %`.padStart(8, ' ')",
        "                                markdownToInject += `${namePad} ${statPad} ${bar} ${percentPad}\\n`",
        "                            })",
        "                        }",
        "                        markdownToInject += '```\\n'",
        "                        break",
        ...(hasWakatime ? [
            "                    case 'waka-10k-hours':",
            "                        markdownToInject = '\\n' + generateWaka10kHoursAscii(wakaData, bConf, config)",
            "                        break"
        ] : []),
        "",
        "                    case 'activity-graph':",
        "                        const agTheme = bConf.activityGraphTheme || config.activityGraphTheme || 'tokyo-night'",
        "                        const agAreaFill = bConf.activityGraphAreaFill !== undefined ? bConf.activityGraphAreaFill : (config.activityGraphAreaFill !== undefined ? config.activityGraphAreaFill : true)",
        "                        const agHideBorder = bConf.activityGraphHideBorder !== undefined ? bConf.activityGraphHideBorder : (config.activityGraphHideBorder || false)",
        "                        const agHideTitle = bConf.activityGraphHideTitle !== undefined ? bConf.activityGraphHideTitle : (config.activityGraphHideTitle || false)",
        "                        const agGrid = bConf.activityGraphGrid !== undefined ? bConf.activityGraphGrid : (config.activityGraphGrid || false)",
        "                        const agDays = bConf.activityGraphDays || config.activityGraphDays || 31",
        "                        const agRadius = bConf.activityGraphRadius !== undefined ? bConf.activityGraphRadius : (config.activityGraphRadius || 0)",
        "                        const agCustomTitle = bConf.activityGraphCustomTitle || config.activityGraphCustomTitle || ''",
        "",
        "                        const agBaseUrl = 'https://github-readme-activity-graph.vercel.app/graph'",
        "                        const agParams = new URLSearchParams({",
        "                            username: config.username,",
        "                            theme: agTheme,",
        "                            area: agAreaFill.toString(),",
        "                            hide_border: agHideBorder.toString(),",
        "                            hide_title: agHideTitle.toString(),",
        "                            grid: agGrid.toString(),",
        "                            days: agDays.toString(),",
        "                            radius: agRadius.toString(),",
        "                        })",
        "                        if (agCustomTitle) {",
        "                            agParams.append('custom_title', agCustomTitle)",
        "                        }",
        "                        const agUrl = `${agBaseUrl}?${agParams.toString()}`",
        "                        markdownToInject = `\\n<a href=\"https://github.com/${config.username}\">\\n    <img src=\"${agUrl}\" alt=\"${config.username}'s GitHub Activity Graph\" width=\"100%\" />\\n</a>\\n`",
        "                        break",
        "                }",
        "",
        "                newReadme = newReadme.substring(0, startIndex + startMarker.length) +",
        "                    markdownToInject.trimEnd() + '\\n' +",
        "                    newReadme.substring(endIndex)",
        "            } else {",
        "                console.warn(`⚠️ Markers not found for widget: ${block.widgetType}`)",
        "            }",
        "        }",
        "",
        "        fs.writeFileSync(README_PATH, newReadme, 'utf-8')",
        "        console.log('✅ README updated successfully!')",
        "    } catch (error) {",
        "        console.error('❌ Failed to update README:', error)",
        "        process.exit(1)",
        "    }",
        "}",
        "",
        "updateReadme()"
    ].join('\n');
}

export function generateGithubFetcherScript(): string {
    return [
        "const GITHUB_TOKEN = process.env.GITHUB_TOKEN || ''",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "async function fetchGithub(url: string, options: any = {}) {",
        "    const res = await fetch(url, {",
        "        ...options,",
        "        headers: {",
        "            'Authorization': `Bearer ${GITHUB_TOKEN}`,",
        "            'Accept': 'application/vnd.github.v3+json',",
        "            ...(options.headers || {})",
        "        }",
        "    })",
        "    if (!res.ok) throw new Error(`GitHub API failed: ${res.status}`)",
        "    return res.json()",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "async function fetchGraphql(query: string, variables: any = {}) {",
        "    const res = await fetch('https://api.github.com/graphql', {",
        "        method: 'POST',",
        "        headers: {",
        "            'Authorization': `Bearer ${GITHUB_TOKEN}`,",
        "            'Content-Type': 'application/json'",
        "        },",
        "        body: JSON.stringify({ query, variables })",
        "    })",
        "    if (!res.ok) throw new Error(`GraphQL fetch failed: ${res.status}`)",
        "    return res.json()",
        "}",
        "",
        "export async function fetchProductiveTime(username: string) {",
        "    try {",
        "        const events = await fetchGithub(`https://api.github.com/users/${username}/events/public?per_page=100`)",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const pushEvents = events.filter((e: any) => e.type === 'PushEvent')",
        "        ",
        "        const timeBuckets = { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "        let totalCommits = 0",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        pushEvents.forEach((event: any) => {",
        "            // Use local runtime timezone (Set via TZ env variable in Github Actions)",
        "            const date = new Date(event.created_at)",
        "            const hour = date.getHours()",
        "",
        "            if (hour >= 6 && hour < 12) timeBuckets.morning++",
        "            else if (hour >= 12 && hour < 18) timeBuckets.daytime++",
        "            else if (hour >= 18 && hour < 24) timeBuckets.evening++",
        "            else timeBuckets.night++",
        "            totalCommits++",
        "        })",
        "        ",
        "        if (totalCommits === 0) {",
        "            return {",
        "                morning: 0, daytime: 0, evening: 0, night: 0,",
        "                commits: { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "            }",
        "        }",
        "        ",
        "        return {",
        "            morning: Math.round((timeBuckets.morning / totalCommits) * 100),",
        "            daytime: Math.round((timeBuckets.daytime / totalCommits) * 100),",
        "            evening: Math.round((timeBuckets.evening / totalCommits) * 100),",
        "            night: Math.round((timeBuckets.night / totalCommits) * 100),",
        "            commits: timeBuckets",
        "        }",
        "    } catch (e) {",
        "        console.warn('Failed to fetch productive time:', e)",
        "        return {",
        "            morning: 0, daytime: 0, evening: 0, night: 0,",
        "            commits: { morning: 0, daytime: 0, evening: 0, night: 0 }",
        "        }",
        "    }",
        "}",
        "",
        "export async function fetchUserRepositories(username: string) {",
        "    try {",
        "        // 1. Fetch Repositories",
        "        const sinceDate = new Date()",
        "        sinceDate.setDate(sinceDate.getDate() - 7)",
        "        ",
        "        const query = `",
        "            query($login: String!) {",
        "                user(login: $login) {",
        "                    repositories(first: 100, isFork: false, orderBy: {field: PUSHED_AT, direction: DESC}) {",
        "                        nodes {",
        "                            name",
        "                            pushedAt",
        "                            languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {",
        "                                edges { size node { name } }",
        "                            }",
        "                        }",
        "                    }",
        "                }",
        "            }",
        "        `",
        "        const { data } = await fetchGraphql(query, { login: username })",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        return data?.user?.repositories?.nodes || []",
        "    } catch (e) {",
        "        console.warn('Failed to fetch repositories:', e)",
        "        return []",
        "    }",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "export function calculateWeeklyLanguages(repos: any[]) {",
        "    try {",
        "        const langMap = new Map()",
        "        let totalBytes = 0",
        "        ",
        "        const sevenDaysAgo = new Date()",
        "        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        for (const repo of repos) {",
        "            if (!repo.languages?.edges) continue",
        "            // Apply 7-day limit",
        "            if (repo.pushedAt && new Date(repo.pushedAt) < sevenDaysAgo) continue",
        "            ",
        "            // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "            for (const { size, node } of repo.languages.edges) {",
        "                const current = langMap.get(node.name) || { size: 0, count: 0 }",
        "                langMap.set(node.name, { size: current.size + size, count: current.count + 1 })",
        "                totalBytes += size",
        "            }",
        "        }",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        const results = Array.from(langMap.entries()).map(([name, val]: any) => ({",
        "            name,",
        "            count: val.count,",
        "            percent: totalBytes > 0 ? Math.round((val.size / totalBytes) * 100 * 100) / 100 : 0",
        "        }))",
        "        ",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        return results.sort((a: any, b: any) => b.percent - a.percent)",
        "    } catch (e) {",
        "        console.warn('Failed to calculate languages:', e)",
        "        return []",
        "    }",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "export async function fetchUserEvents(username: string) {",
        "    try {",
        "        const events: any[] = []",
        "        for (let page = 1; page <= 3; page++) {",
        "            const data = await fetchGithub(`https://api.github.com/users/${username}/events/public?per_page=100&page=${page}`)",
        "            events.push(...data)",
        "            if (data.length < 100) break",
        "        }",
        "        return events",
        "    } catch(e) {",
        "        return []",
        "    }",
        "}",
        "",
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "export function calculateWeeklyProjects(events: any[]) {",
        "    try {",
        "        const projectMap = new Map<string, number>()",
        "        let totalCount = 0",
        "        ",
        "        const sevenDaysAgo = new Date()",
        "        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)",
        "        // eslint-disable-next-line @typescript-eslint/no-explicit-any",
        "        events.forEach((event: any) => {",
        "            if (!event.created_at || new Date(event.created_at) < sevenDaysAgo) return",
        "            let count = 0",
        "            if (event.type === 'PushEvent') {",
        "                count = event.payload?.commits?.length || event.payload?.size || 1",
        "            } else if (event.type === 'PullRequestEvent') {",
        "                const action = event.payload?.action",
        "                if (action === 'opened' || action === 'closed') count = 1",
        "            } else if (event.type === 'CreateEvent') {",
        "                count = 1",
        "            }",
        "            if (count > 0) {",
        "                const repoName = event.repo?.name?.split('/')[1] || event.repo?.name",
        "                projectMap.set(repoName, (projectMap.get(repoName) || 0) + count)",
        "                totalCount += count",
        "            }",
        "        })",
        "        ",
        "        if (totalCount === 0) return []",
        "        ",
        "        const results = Array.from(projectMap.entries()).map(([name, count]) => ({",
        "            name,",
        "            commits: count,",
        "            percent: Math.round((count / totalCount) * 100 * 100) / 100",
        "        }))",
        "        ",
        "        return results.sort((a, b) => b.commits - a.commits)",
        "    } catch (e) {",
        "        console.warn('Failed to calculate projects:', e)",
        "        return []",
        "    }",
        "}"
    ].join('\n');

}

export function generatePackageJson(): string {
    return [
        "{",
        "  \"name\": \"github-profile-automation\",",
        "  \"version\": \"1.0.0\",",
        "  \"description\": \"Auto-updater for Glossy GitHub Profile\",",
        "  \"main\": \"scripts/update-readme.ts\",",
        "  \"scripts\": {",
        "    \"update-profile\": \"ts-node scripts/update-readme.ts\"",
        "  },",
        "  \"dependencies\": {",
        "    \"ts-node\": \"^10.9.1\",",
        "    \"typescript\": \"^5.0.0\",",
        "    \"@types/node\": \"^18.0.0\"",
        "  },",
        "  \"ts-node\": {",
        "    \"compilerOptions\": {",
        "      \"module\": \"CommonJS\"",
        "    }",
        "  }",
        "}"
    ].join('\n');
}

export function generateTsConfig(): string {
    return [
        "{",
        "  \"compilerOptions\": {",
        "    \"target\": \"ES2022\",",
        "    \"module\": \"CommonJS\",",
        "    \"moduleResolution\": \"node\",",
        "    \"esModuleInterop\": true,",
        "    \"skipLibCheck\": true,",
        "    \"forceConsistentCasingInFileNames\": true",
        "  }",
        "}"
    ].join('\n');
}

export function generateWakatimeFetcherScript(): string {
    return [
        "const WAKATIME_API_KEY = process.env.WAKATIME_API_KEY || ''",
        "",
        "export async function fetchWakatimeStats() {",
        "    try {",
        "        if (!WAKATIME_API_KEY) throw new Error('WAKATIME_API_KEY is not defined')",
        "        const encodedKey = Buffer.from(WAKATIME_API_KEY).toString('base64')",
        "        const ranges = ['all_time', 'last_year', 'last_7_days']",
        "        let finalData: any = null",
        "        let finalRange = 'unknown'",
        "        let isCalculating = false",
        "",
        "        for (const range of ranges) {",
        "            const response = await fetch(`https://wakatime.com/api/v1/users/current/stats/${range}`, {",
        "                headers: { 'Authorization': `Basic ${encodedKey}` },",
        "                cache: 'no-store'",
        "            })",
        "            if (response.status === 202) {",
        "                isCalculating = true",
        "                finalRange = range",
        "                break",
        "            }",
        "            if (response.ok) {",
        "                const data = await response.json()",
        "                const langs = data.data?.languages || []",
        "                if (langs.length > 0) {",
        "                    finalData = data",
        "                    finalRange = range",
        "                    break",
        "                }",
        "            }",
        "        }",
        "",
        "        if (isCalculating) {",
        "            return {",
        "                success: true,",
        "                isCalculating: true,",
        "                timeRange: finalRange,",
        "                languages: []",
        "            }",
        "        }",
        "",
        "        let languages = finalData?.data?.languages || []",
        "        const isIncludingToday = finalData?.data?.is_including_today ?? false",
        "",
        "        if (!isIncludingToday) {",
        "            try {",
        "                const todayStr = new Date().toISOString().split('T')[0]",
        "                const summariesResponse = await fetch(`https://wakatime.com/api/v1/users/current/summaries?start=${todayStr}&end=${todayStr}`, {",
        "                    headers: { 'Authorization': `Basic ${encodedKey}` },",
        "                    cache: 'no-store'",
        "                })",
        "                if (summariesResponse.ok) {",
        "                    const todayData = await summariesResponse.json()",
        "                    const todayLangs = todayData.data?.[0]?.languages || []",
        "                    if (todayLangs.length > 0) {",
        "                        const mergedLangsMap = new Map()",
        "                        for (const lang of languages) {",
        "                            mergedLangsMap.set(lang.name, { ...lang, total_seconds: lang.total_seconds })",
        "                        }",
        "                        for (const todayLang of todayLangs) {",
        "                            if (mergedLangsMap.has(todayLang.name)) {",
        "                                mergedLangsMap.get(todayLang.name).total_seconds += todayLang.total_seconds",
        "                            } else {",
        "                                mergedLangsMap.set(todayLang.name, { name: todayLang.name, total_seconds: todayLang.total_seconds })",
        "                            }",
        "                        }",
        "                        languages = Array.from(mergedLangsMap.values()).sort((a, b) => b.total_seconds - a.total_seconds)",
        "                    }",
        "                }",
        "            } catch (mergeError) {",
        "                console.error('Failed to merge today summary:', mergeError)",
        "            }",
        "        }",
        "",
        "        if (languages.length === 0) {",
        "            return {",
        "                success: true,",
        "                isCalculating: false,",
        "                timeRange: finalRange === 'unknown' ? 'today' : finalRange,",
        "                languages: []",
        "            }",
        "        }",
        "",
        "        return {",
        "            success: true,",
        "            isCalculating: false,",
        "            timeRange: finalRange === 'unknown' ? 'today' : finalRange,",
        "            languages",
        "        }",
        "    } catch (e: any) {",
        "        console.error('WakaTime Fetcher Error:', e.message)",
        "        return { success: false, languages: [] }",
        "    }",
        "}"
    ].join('\n');
}
