import { useState, useCallback, useEffect } from 'react'
import { generateMarkdown } from '@/entities/profile/lib/markdown/generator'
import { transformStoreToConfig } from '@/entities/profile/lib/mappers'
import { useProfileStore } from '@/entities/profile/model/useProfileStore'
import { useBlockStore } from '@/entities/block/model/useBlockStore'
import { Block } from '@/entities/block/model/types'
import { generateProfileUpdateWorkflow } from './workflowGenerator'
import { generateReadmeUpdaterScript, generateGithubFetcherScript, generatePackageJson, generateTsConfig } from './scriptGenerator'

export function useProfileExport() {
    const [isCopied, setIsCopied] = useState(false)
    const [markdown, setMarkdown] = useState('')

    const store = useProfileStore()
    const blocks = useBlockStore((state) => state.blocks)

    useEffect(() => {
        const config = {
            ...transformStoreToConfig(store),
            blocks
        }
        setMarkdown(generateMarkdown(config))
    }, [store, blocks])

    const ACTIONS_REQUIRED_WIDGETS = ['productive-time', 'weekly-languages', 'weekly-projects']
    const hasDynamicFeatures = blocks.some((b: any) => b.type === 'widget' && ACTIONS_REQUIRED_WIDGETS.includes(b.widgetType || b.id))

    const copyToClipboard = useCallback(async () => {
        try {
            await navigator.clipboard.writeText(markdown)
            setIsCopied(true)
            setTimeout(() => setIsCopied(false), 2000)
        } catch (err) {
            console.error('Failed to copy to clipboard:', err)
        }
    }, [markdown])

    const handleDownload = useCallback(async () => {
        try {
            const { saveAs } = await import('file-saver')

            if (!hasDynamicFeatures) {
                // Static Mode: Backup Config + README in ZIP
                const config = {
                    ...transformStoreToConfig(store),
                    blocks
                }
                const JSZip = (await import('jszip')).default
                const zip = new JSZip()

                zip.file("README.md", markdown)
                zip.file("glossy-config.json", JSON.stringify(config, null, 2))

                const content = await zip.generateAsync({ type: "blob" })
                saveAs(content, `github-profile-static.zip`)
                return
            }

            // Dynamic Mode: Full ZIP package
            const JSZip = (await import('jszip')).default

            const zip = new JSZip()

            // 0. Initial README.md with markers
            zip.file("README.md", markdown)

            // 1. Config JSON (SSOT)
            const config = {
                ...transformStoreToConfig(store),
                blocks
            }
            const configString = JSON.stringify(config, null, 2)
            zip.file("glossy-config.json", `// DO NOT EDIT THIS FILE MANUALLY. If you want to change your profile design, please upload this config to the Glossy Editor, edit it visually, and export it again.\n${configString}`)

            // 2. Action YAML (Alarm Clock)
            const username = store.username || 'your-username'
            // For now, defaulting cron to daily in the hook since we haven't passed cron from modal yet (Will update shortly in modal)
            const cronFrequency = store.exportCronFrequency || '0 0 * * *'
            const workflow = generateProfileUpdateWorkflow(username, cronFrequency)
            zip.file(".github/workflows/glossy-update.yml", workflow)

            // 3. Scripts directory
            const scriptsFolder = zip.folder("scripts")
            if (scriptsFolder) {
                scriptsFolder.file("update-readme.ts", generateReadmeUpdaterScript())
                scriptsFolder.file("github-fetcher.ts", generateGithubFetcherScript())
            }

            // 4. Package.json & tsconfig.json
            zip.file("package.json", generatePackageJson())
            zip.file("tsconfig.json", generateTsConfig())

            // 5. Build ZIP
            const content = await zip.generateAsync({ type: "blob" })
            saveAs(content, `github-profile-action.zip`)

        } catch (err: unknown) {
            console.error('Failed to download:', err)
            const errorMessage = err instanceof Error ? err.message : 'Unknown error'
            alert(`Failed to generate export: ${errorMessage}. Please try again.`)
        }
    }, [store, blocks, hasDynamicFeatures, markdown])

    // --- IMPORT LOGIC ---
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const restoreConfig = useCallback((importedConfig: any) => {
        try {
            // Restore Profile Store fields
            if (importedConfig.username !== undefined) useProfileStore.setState({ username: importedConfig.username })
            if (importedConfig.theme !== undefined) useProfileStore.setState({ theme: importedConfig.theme })
            if (importedConfig.selectedTemplate !== undefined) useProfileStore.setState({ selectedTemplate: importedConfig.selectedTemplate })

            if (importedConfig.bio) useProfileStore.setState({ bio: importedConfig.bio })
            if (importedConfig.productiveTime) useProfileStore.setState({ productiveTime: importedConfig.productiveTime })

            if (importedConfig.activityGraphTheme !== undefined) useProfileStore.setState({ activityGraphTheme: importedConfig.activityGraphTheme })
            if (importedConfig.activityGraphAreaFill !== undefined) useProfileStore.setState({ activityGraphAreaFill: importedConfig.activityGraphAreaFill })
            if (importedConfig.activityGraphHideBorder !== undefined) useProfileStore.setState({ activityGraphHideBorder: importedConfig.activityGraphHideBorder })
            if (importedConfig.activityGraphHideTitle !== undefined) useProfileStore.setState({ activityGraphHideTitle: importedConfig.activityGraphHideTitle })
            if (importedConfig.activityGraphGrid !== undefined) useProfileStore.setState({ activityGraphGrid: importedConfig.activityGraphGrid })
            if (importedConfig.activityGraphDays !== undefined) useProfileStore.setState({ activityGraphDays: importedConfig.activityGraphDays })
            if (importedConfig.activityGraphRadius !== undefined) useProfileStore.setState({ activityGraphRadius: importedConfig.activityGraphRadius })
            if (importedConfig.activityGraphCustomTitle !== undefined) useProfileStore.setState({ activityGraphCustomTitle: importedConfig.activityGraphCustomTitle })

            if (importedConfig.weeklyLanguages) useProfileStore.setState({ weeklyLanguages: importedConfig.weeklyLanguages })
            if (importedConfig.weeklyProjects) useProfileStore.setState({ weeklyProjects: importedConfig.weeklyProjects })

            // Restore Block Store (Canvas UI)
            if (Array.isArray(importedConfig.blocks)) {
                useBlockStore.setState({ blocks: importedConfig.blocks as Block[] })
            }

            return true
        } catch (error: unknown) {
            console.error('Error restoring config:', error)
            return false
        }
    }, [])

    // Store frequency globally for ZIP export
    const setExportCronFrequency = useCallback((cron: string) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        useProfileStore.setState({ exportCronFrequency: cron } as any)
    }, [])

    return { markdown, copyToClipboard, handleDownload, isCopied, hasDynamicFeatures, restoreConfig, setExportCronFrequency }
}
